### ISSUE TITLE
Pre-process input error with a multiple chromosome file like 'GRCh38.p12.genome.fa'

### ISSUE THREAD

**Issue by zhixue** [lykaust15/DeepSimulator#33]
Hi Li:   

Thank you for your good work on simulating nanopore sequencing.  
I have built a docker of 'DeepSimulator v1.5 [Jun-29-2019]', and pass the example without error.   
When I use 'GRCh38.p12.genome.fa' (a multiple chromosome file), command like:
```bash
docker run -i -v `pwd`/out:/data deepsimulator ./deep_simulator.sh -i /data/GRCh38.p12.genome.fa -o /data/n_100 -c 16 -B 2 -n 100
```
 it has the error as follow:
```log
Pre-process input genome...
Traceback (most recent call last):
  File "/DeepSimulator/util/genome_preprocess.py", line 54, in <module>
    genome = replace_n(genome)
  File "/DeepSimulator/util/genome_preprocess.py", line 25, in replace_n
    genome_list = np.array([x for x in genome])
ValueError: could not convert string to float: N
Pre-process input genome done!
```
I have checked the issues, guessing the problem i met like [this](https://github.com/lykaust15/DeepSimulator/issues/30). The muiltple contig/chromosome file need to be separated into several single contig/chromosome files. Then you said that you have done(testing with 'example/multi.fasta' ), can you update soon with the example of 'multi.fasta' in deepsimulator's home page? 

Thanks!

**Comment by lykaust15** [comment]
Hi, thank you for reporting the issue. 
The branch has been merged. You can `git pull` and check again.

**Comment by zhixue** [comment]
Thank you for your rapid answer. I check again and run "mult.fasta" sucessfully!
However it still has the same error when running "GRCh38" (servral minutes after "Pre-process input genome...", see detail)
Might the lines with ">" in fasta file influence the step of pre processing? 
```
# ls -lh /data/
total 3.0G
-rwxrwxrwx 1 root root 3.0G Oct 28 06:01 GRCh38.p12.genome.fa
# grep '>' example/multi.fasta
>0 | 1000000 19463748-20463748 of 50818468
>0 | 1000000 19463748-20463748 of 50818469
# grep '>' /data/GRCh38.p12.genome.fa 
>chr1 1
>chr2 2
>chr3 3
...
>chrY Y
>chrM MT
```
-----------------------
#### Detail:
no error in example with command `./deep_simulator.sh -i example/multi.fasta -o test -B 2 -n 100
`
```
Pre-process input genome...
Pre-process input genome done!
Executing the preprocessing step...
('The average length is: ', 822.27999999999997)
('The average length is: ', 1262.3699999999999)
Finished the preprocessing step!
Key parameters for simulation are shown below 
    event_std    : 1.0 
    filter_freq  : 950 
    signal_std   : 1.0 
Running the context-independent pore model...
100%|████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:05<00:00, 38.33it/s]
Finished generate the simulated signals and fast5 files!
Running Basecalling...
   Basecalling with Guppy_CPU...
ONT Guppy basecalling software version 3.1.5+781ed57
config file:        /DeepSimulator/base_caller/guppy_3.1.5/ont-guppy-cpu/data/dna_r9.4.1_450bps_hac.cfg
model file:         /DeepSimulator/base_caller/guppy_3.1.5/ont-guppy-cpu/data/template_r9.4.1_450bps_hac.jsn
input path:         /DeepSimulator/test/fast5
save path:          /DeepSimulator/test/fastq
chunk size:         1000
chunks per runner:  1000
records per file:   4000
num basecallers:    1
cpu mode:           ON
threads per caller: 8

Found 200 fast5 files to process.
Init time: 1925 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Caller time: 33726 ms, Samples called: 1767985, samples/s: 52422
Finishing up any open output files.
Failed to send ping to https://ping.oxfordnanoportal.com/basecall: Couldn't resolve host 'ping.oxfordnanoportal.com': Couldn't resolve host name
Basecalling completed successfully.
Basecalling finished!
Checking the read accuracy...
Here is the mapping identity: 0.916413 of 200 (pass 200 + fail 0) reads passed base-calling.
```

error when running 'GRCh38' with command `./deep_simulator.sh -i /data/GRCh38.p12.genome.fa -o n_100 -B 2 -n 100`
```
Pre-process input genome...
Traceback (most recent call last):
  File "/DeepSimulator/util/genome_preprocess.py", line 88, in <module>
    genome = replace_n(genome)
  File "/DeepSimulator/util/genome_preprocess.py", line 57, in replace_n
    genome_list = np.array([x for x in genome])
ValueError: could not convert string to float: N
Pre-process input genome done!
Executing the preprocessing step...
ls: cannot access '/DeepSimulator/n_100/processed_genome*': No such file or directory
cat: '/DeepSimulator/n_100/sampled_read_*': No such file or directory
Finished the preprocessing step!
Key parameters for simulation are shown below 
    event_std    : 1.0 
    filter_freq  : 950 
    signal_std   : 1.0 
Running the context-independent pore model...
0it [00:00, ?it/s]
Finished generate the simulated signals and fast5 files!
Running Basecalling...
   Basecalling with Guppy_CPU...
ONT Guppy basecalling software version 3.1.5+781ed57
config file:        /DeepSimulator/base_caller/guppy_3.1.5/ont-guppy-cpu/data/dna_r9.4.1_450bps_hac.cfg
model file:         /DeepSimulator/base_caller/guppy_3.1.5/ont-guppy-cpu/data/template_r9.4.1_450bps_hac.jsn
input path:         /DeepSimulator/n_100/fast5
save path:          /DeepSimulator/n_100/fastq
chunk size:         1000
chunks per runner:  1000
records per file:   4000
num basecallers:    1
cpu mode:           ON
threads per caller: 8

Found 0 fast5 files to process.
Init time: 2073 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Caller time: 101 ms, Samples called: 0, samples/s: 0
Finishing up any open output files.
Basecalling completed successfully.
Basecalling finished!
Checking the read accuracy...
Here is the mapping identity: -nan of 0 (pass 0 + fail 0) reads passed base-calling.
```

**Comment by zhixue** [comment]
I think it is caused by the base 'N' in the file, I will try other strategies to handle the 'N'.

**Comment by lykaust15** [comment]
Hi, as far as I can see, the error seems to come from the content of the file. I guess there are some bases other than 'ATCGN', right?

**Comment by lykaust15** [comment]
> I think it is caused by the base 'N' in the file, I will try other strategies to handle the 'N'.

Simple 'N' should be fine. Not sure about the specific format. I guess your file has space before N.

**Comment by lykaust15** [comment]
I just added some 'N' into `multi.fasta`. It can pass the test. You can `git pull` and have a try.

**Comment by zhixue** [comment]
I found the reason that [the dtype of numpy.array](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.array.html) will change if the length of array quickly grows.  
for example:  
```
>>> print(numpy.array(['A','N','T','N']*int(10**3)))
array(['A', 'N', 'T', ..., 'T', 'G', 'N'], dtype='|S1')
>>> print(len(numpy.array(['A','N','T','N']*int(10**3))))
4000
>>> print(len(numpy.array(['A','N','T','N']*int(10**9))))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: A
```
If change File "/DeepSimulator/util/genome_preprocess.py", line 57, in replace_n
```python
    genome_list = np.array([x for x in genome], dtype='|S1')
```
It worked and generated 2400  records of sequence but at the cost of more than 100GB RAM to simulating 3*10^9 sequence bases, I think some other smaller type(like int8) is required to store these 5 bases ('A','C','G','T','N') if 'numpy array' need to be used.  

----------------------------
Another problem is that the 2400 records of sequence are from only a few chromosomes like:
```
$ ./deep_simulator.sh -i /data/GRCh38.p12.genome.fa -o testn_100 -c 16 -B 2 -n 100  
...
Here is the mapping identity: 0.912393 of 2400 (pass 2400 + fail 0) reads passed base-calling.
$ cat testn_100/mapping.paf | awk '{print $6}'| sort | uniq -c
   2000 chr22
    400 chr3
```

Thank you 🐮🍺~

**Comment by lykaust15** [comment]
Hi,
the numpy problem should have been solved. You can `git pull` and `git checkout h38`. Please double-check it.
As for the second problem. You can check the sample reads, which have not gone through the pore model. In our methods, the sample reads are generated randomly, which should not have the problem you reported. My initial guess is that during mapping, the mapping algorithm maps most of the simulated sequence to chr22 since chr22 is short and easy. I will check this problem in detail. Feel free to report any further finds and issues you get. Also, feel free to `git push` if you think you would like to contribute to this repo.

**Comment by lykaust15** [comment]
Here is the output when running against hg38 original files, which contains 639 contigs and contains more than 3 billion bases. This large scale exp works fine to me. 

```
(tensorflow_cdpm) [liy0f@kw60226 DeepSimulator]$ ./deep_simulator.sh -i example/h38.fa 
Pre-process input genome...
Pre-process input genome done!
Executing the preprocessing step...
('The average length is: ', 7981.6000000000004)
('The average length is: ', 7981.6000000000004)
('The average length is: ', 7981.6000000000004)

...OMIT many lines here.

('The average length is: ', 7981.6000000000004)
('The average length is: ', 3382.0599999999999)
('The average length is: ', 2191.79)
('The average length is: ', 2114.1900000000001)
('The average length is: ', 2007.8199999999999)
Finished the preprocessing step!
Key parameters for simulation are shown below 
    event_std    : 1.0 
    filter_freq  : 950 
    signal_std   : 1.0 
Running the context-independent pore model...
 28%|█████████▊                         | 17947/63900 [07:25<18:59, 40.31it/s]
```
